### ISSUE TITLE
Normalize intro text styling

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/eto-supply-chain#393]
See https://github.com/georgetown-cset/science_map_ui/issues/309

**Comment by jmelot** [comment]
@za158 the remaining difference between what we're doing here and in the MoS seems to be letter spacing. The difference is very subtle but you can see it with this side-by-side comparison. Which do you prefer?

<img width="974" alt="Screen Shot 2022-12-13 at 11 34 24 AM" src="https://user-images.githubusercontent.com/1252409/207390804-01d87ea3-d4fa-446e-9365-12b1600ef0e8.png">
<img width="983" alt="Screen Shot 2022-12-13 at 11 34 50 AM" src="https://user-images.githubusercontent.com/1252409/207390820-d3c106a6-d38a-44d8-bf74-d48b9dfedb9c.png">

**Comment by jmelot** [comment]
(Neha the first image is with current letter spacing of 0.0075em and the second is with letter spacing unset)

**Comment by za158** [comment]
#2, thanks
---
Zachary Arnold
Analytic Lead, Emerging Technology Observatory
Center for Security and Emerging Technology
***@***.***
